# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56d7520a7592f5f054e519649a648cdacd3888510556527fcb4ee1e29c5421cf7b42a3fea3a2e0a6c6cfba0df9ebac7e6d24df169a473efd6c60769a261a685c

test:
  secret_key_base: 3824836afe604a30b4e32e6cbf9b838db7f3bb9d87f51ef88fee9c29c16d6d631588c89b9db412d5256e412d11e2d33d0360fce1ea1a6e289c1bd3a992154f26

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
